export const APP_META_DATA = {
  siteName: 'サイト名',
  siteDescription: ['サイトの説明文'],
  owner: 'owner-name',
};
export const COLOR = {
  background: '#333333',
  background_2: '#F9F9F9',
  white: '#FFFFFF',
  blue: '#1A3B87',
  green: '#6FCF97',
  orange: '#FFA361',
  red: '#FF6A61',
  yellow: '#FFC961',
  gray_1: '#9C9C9C',
  gray_2: '#D9D9D9',
  gray_3: '#EDEDED',
  blue_1: '#6C97FA',
  blue_2: '#A2BCFA',
  blue_3: '#E6EEFF',
  blue_bg: '#F5F9FE',
  black: '#333333',
} as const satisfies { [key: string]: `#${string}` };

export const FORM_ERROR_MESSAGE = {
  INVALID_EMAIL: 'メールの形式で入力してください',
  INVALID_PASSWORD: 'パスワードは半角英数大文字小文字を含む8文字以上で入力してください',
  REQUIRED: '入力してください',
};

export const FOURSQUARE_BACKEND = 'https://api.foursquare.com' as const;

export const FOURSQUARE_API_VERSION = 20230404 as const;

export const FOURSQUARE_AUTH_URL = `https://foursquare.com/oauth2/authenticate?client_id=${process.env.NEXT_PUBLIC_CLIENT_ID}&response_type=code&redirect_uri=${process.env.NEXT_PUBLIC_REDIRECT_URI}`;
export const PREFECTURES = {
  北海道: 1,
  青森県: 2,
  岩手県: 3,
  宮城県: 4,
  秋田県: 5,
  山形県: 6,
  福島県: 7,
  茨城県: 8,
  栃木県: 9,
  群馬県: 10,
  埼玉県: 11,
  千葉県: 12,
  東京都: 13,
  神奈川県: 14,
  新潟県: 15,
  富山県: 16,
  石川県: 17,
  福井県: 18,
  山梨県: 19,
  長野県: 20,
  岐阜県: 21,
  静岡県: 22,
  愛知県: 23,
  三重県: 24,
  滋賀県: 25,
  京都府: 26,
  大阪府: 27,
  兵庫県: 28,
  奈良県: 29,
  和歌山県: 30,
  鳥取県: 31,
  島根県: 32,
  岡山県: 33,
  広島県: 34,
  山口県: 35,
  徳島県: 36,
  香川県: 37,
  愛媛県: 38,
  高知県: 39,
  福岡県: 40,
  佐賀県: 41,
  長崎県: 42,
  熊本県: 43,
  大分県: 44,
  宮崎県: 45,
  鹿児島県: 46,
  沖縄県: 47,
} as const;
